# Generated by Django 6.0.3 on 2026-03-16 03:39

import django.db.models.deletion
import projects.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(default=projects.models.generate_slug, help_text='Identificador único del proyecto', max_length=10, unique=True)),
                ('title', models.CharField(blank=True, help_text='Título del proyecto', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Descripción del proyecto')),
                ('content_type', models.CharField(default='unknown', help_text='Tipo de contenido (code, image, db, error, etc)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Fecha de expiración (null = no expira)', null=True)),
                ('views', models.IntegerField(default=0, help_text='Número de veces visto')),
                ('is_incognito', models.BooleanField(default=False, help_text='Modo incógnito (no guardar usuario)')),
                ('password', models.CharField(blank=True, help_text='Contraseña opcional para acceder', max_length=128)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['-created_at'],
            },
        ),
    ]
